spring:
  application:
    name: travel-account

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel_account?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: travel
    password: travel1234

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.yh.travel.domain
  configuration:
    map-underscore-to-camel-case: true
    local-cache-scope: STATEMENT